apiVersion: apps/v1
kind: Deployment
metadata:
  name: elb-controller
  namespace: zcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elb-controller
  template:
    metadata:
      name: elb-controller
      labels:
        app: elb-controller
    spec:
      serviceAccount: zcloud-cluster-admin
      containers:
      - name: elb-controller
        image: zdnscloud/elb-controller:v0.0.1
        command: 
          - /elbc
        args:
          - -server
          - 192.168.134.101
          - -user
          - admin
          - -password
          - radware
          - -cluster
          - local